spring.application.name=shaleen

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=shaleen
spring.datasource.password=Shaleen@794
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Logging Level
logging.level.root=INFO

logging.level.com.urlshortener.shaleen=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
logging.file.name=logs/url-shortener.log

#Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
